import './styles/core.css';
import './styles/app.css';
import './styles/swiper.min.css';
import './scripts/jquery-1.9.1.min.js';
import './scripts/scripts.js';
import './scripts/jquery.slides.min.js';
import './scripts/jquery.lazyload.min.js';
import './scripts/swiper.jquery.min.js';
import './scripts/jquery.page.js';
